name: Node CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm install
      # The owning team will fix the issues and uncomment the steps after necessary linting and configuring changes
      #- name: Lint
      #  run: npm run lint

     # - name: Test
     #   run: |
     #     npm run test_compile
     #     npm run test_comments
